version: "3.7"

services:

  image-framer:
    container_name: image-framer
    image: image-framer:latest
    build:
      context: .
      dockerfile: Dockerfile
    # We don't need this port open in prod, but if you do:
    #ports:
    #  - "127.0.0.1:9053:9053"

networks:
  default:
    name: tz1and_prod